name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-26

    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: |
        swift build -c release
        mkdir -p xPDF.app/Contents/MacOS
        cp .build/arm64-apple-macosx/release/xPDF xPDF.app/Contents/MacOS/
        tar -cJf xPDF.app.tar.xz xPDF.app
    - uses: actions/upload-artifact@v7
      with:
        path: xPDF.app.tar.xz
